### ISSUE TITLE
Epic: ember-data 1.13+ support

### ISSUE THREAD

**Issue by bantic** [201-created/ember-data-hal-9000#22]
An issue to keep track of steps to take to be fully compatible with modern ember data.
The work for this is happening on [ember-data-1-13-support](https://github.com/201-created/ember-data-hal-9000/tree/ember-data-1-13-support).

  * [ ] restructure incoming payloads to JSON API (nearly finished, will build on #19)
  * [ ] parse `_link`'s properly (not sure if this requires supporting CURIEs or if that can happen later)
  * [ ] handle meta data

**Comment by magg** [comment]
+1

**Comment by bantic** [comment]
version `0.3.0-beta.2` is available which should provide support for ember-data 1.13.4 and above. @magg ^^ feel free to give it a try! (More info on #25 and #24)
